# Generated by Django 6.0.5 on 2026-05-14 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(default='Motor Industrial', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Leitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('rms', models.FloatField()),
                ('fft_frequencias', models.JSONField()),
                ('fft_amplitudes', models.JSONField()),
                ('envelope_sinal', models.JSONField()),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.ativo')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
