# Generated by Django 6.0.5 on 2026-05-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroVibracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.CharField(help_text='Tag do sensor. Ex: SENS_MOT_01', max_length=50)),
                ('maquina_nome', models.CharField(default='Motor Industrial - Banco MFPT', max_length=100)),
                ('v_rms', models.FloatField(help_text='Velocidade RMS em mm/s (Métrica de Severidade ISO 10816-3)')),
                ('acc_rms', models.FloatField(help_text='Aceleração RMS global em g (Métrica de energia global)')),
                ('kurtosis', models.FloatField(help_text='Kurtose do sinal (Indicador de impactos agudos / falha de rolamento)')),
                ('skewness', models.FloatField(help_text='Assimetria do sinal (Indicador de desgaste não uniforme)')),
                ('status_iso', models.CharField(choices=[('NORMAL', 'Normal'), ('ALERTA', 'Alerta'), ('CRÍTICO', 'Crítico')], help_text='Status automático baseado nos limites da norma', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Data e hora exata da coleta dos dados')),
            ],
            options={
                'verbose_name': 'Registro de Vibração',
                'verbose_name_plural': 'Registros de Vibração',
                'ordering': ['-timestamp'],
            },
        ),
    ]
