# Generated by Django 6.0.5 on 2026-05-18 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_registrovibracao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leitura',
            name='ativo',
        ),
        migrations.DeleteModel(
            name='Ativo',
        ),
        migrations.DeleteModel(
            name='Leitura',
        ),
    ]
